### ISSUE TITLE
How to use media query in CSS

### ISSUE THREAD

**Issue by onmyway133** [onmyway133/blog#314]
```css
<meta name="viewport" content="width=device-width, initial-scale=1.0">

@media only screen and (max-width: 600px) {
  div.container {
    margin: 0 auto;
      width: 70%;
      margin-top: 60%;
    }     
}
```
