### ISSUE TITLE
How to make simple grid gallery in css

### ISSUE THREAD

**Issue by onmyway133** [onmyway133/blog#642]
```css
div.cards {
  display: flex;
  justify-content: center;
  flex-direction: row;
  flex-wrap: wrap;
  margin-top: 10%;
}

div.card {
  overflow: hidden;
  float: left;
  width: 220px;
  color: #232330;
  text-align: center;
  border-radius: 10px;
  border-color: silver;
  box-shadow: 1px 8px 8px rgba(10, 10, 10, 0.2);
  font-family: 'Open Sans', sans-serif;
  margin: 16px;
  transition: all .2s ease-in-out;
}

div.card:hover {
  transform: scale(1.2);
}
```
