### ISSUE TITLE
How to add under highlight to text in css

### ISSUE THREAD

**Issue by onmyway133** [onmyway133/blog#701]
Use mark. This does not work for multiline

```css
<p>
    <mark css={css`
        display: inline-block;
        line-height: 0em;
        padding-bottom: 0.5em;
        `}>{feature.title}
    </mark>
</p>
```

Another way is to use background

```css
.highlight {
  background: linear-gradient(180deg,rgba(255,255,255,0) 50%, #FFD0AE 50%);
}
```

## Read more

- https://beatrizcaraballo.com/blog/low-highlight-heading-links-squarespace
- https://stackoverflow.com/questions/43683187/how-can-i-create-custom-underline-or-highlight-for-text-in-html-or-css
